"""Mock Audio Adapter for The Inconvenient Vault.

Provides simulated acoustic waveform synthesis and utterance recording
without physical sound cards, PyAudio, or microphones.
"""

import hashlib
from typing import Optional
import numpy as np

from app.interfaces.audio import AudioCaptureInterface


class MockAudioAdapter(AudioCaptureInterface):
    """Synthetic audio capture adapter providing simulated speech waveforms and speaker formants."""

    def __init__(
        self,
        default_speaker_seed: int = 42,
        default_sample_rate: int = 16000,
    ) -> None:
        """Initialize the mock audio adapter.

        Args:
            default_speaker_seed: Identifier seed for default acoustic voice print.
            default_sample_rate: Audio sampling frequency in Hz.
        """
        self._is_available: bool = True
        self._default_speaker_seed: int = default_speaker_seed
        self._sample_rate: int = default_sample_rate
        self._custom_audio: Optional[np.ndarray] = None

    def is_available(self) -> bool:
        """Return whether the simulated audio stream is available."""
        return self._is_available

    def release(self) -> None:
        """Simulate releasing audio recording resources."""
        self._is_available = False
        self._custom_audio = None

    def set_offline(self, offline: bool = True) -> None:
        """Toggle virtual microphone offline/online availability."""
        self._is_available = not offline

    def set_audio(self, audio_data: np.ndarray) -> None:
        """Inject a specific NumPy audio waveform to be returned by record_utterance()."""
        self._custom_audio = audio_data.copy().astype(np.float32)

    def record_utterance(
        self, duration_sec: float = 2.0, sample_rate: Optional[int] = None
    ) -> Optional[np.ndarray]:
        """Record the configured synthetic speech utterance.

        Args:
            duration_sec: Length of utterance in seconds.
            sample_rate: Optional sample rate override.

        Returns:
            Optional[np.ndarray]: 1D float32 audio waveform in [-1.0, 1.0], or None if offline.
        """
        if not self._is_available:
            return None

        if self._custom_audio is not None:
            return self._custom_audio.copy()

        sr = sample_rate or self._sample_rate
        return self.generate_synthetic_utterance(
            speaker_seed=self._default_speaker_seed,
            duration_sec=duration_sec,
            sample_rate=sr,
        )

    def generate_synthetic_utterance(
        self,
        speaker_seed: int = 42,
        phrase: str = "OPEN SESAME OVERENGINEERED",
        duration_sec: float = 2.0,
        sample_rate: int = 16000,
        noise_level: float = 0.01,
    ) -> np.ndarray:
        """Generate a deterministic synthetic speech waveform with speaker-specific formants.

        Synthesizes pitch fundamental (F0) and vocal tract resonances (F1, F2, F3)
        modulated by a rhythmic syllabic amplitude envelope corresponding to the phrase.

        Args:
            speaker_seed: Unique identifier seed determining vocal tract characteristics.
            phrase: Challenge phrase string modulating amplitude envelope.
            duration_sec: Total duration in seconds.
            sample_rate: Sampling frequency in Hz.
            noise_level: Acoustic background noise variance.

        Returns:
            np.ndarray: 1D float32 array normalized to [-1.0, 1.0].
        """
        h_bytes = hashlib.sha256(f"speaker_voice_{speaker_seed}".encode()).digest()
        v = [int(b) for b in h_bytes]
        rng = np.random.RandomState(v[0] * 256 + v[1])

        num_samples = int(duration_sec * sample_rate)
        t = np.linspace(0, duration_sec, num_samples, endpoint=False, dtype=np.float32)

        # 1. Speaker fundamental frequency F0 (100 Hz to 240 Hz)
        f0 = 100.0 + float(v[2] % 140)

        # 2. Vocal formants F1, F2, F3 (vowel resonance peaks)
        f1 = 400.0 + float(v[3] % 400)
        f2 = 1200.0 + float(v[4] % 900)
        f3 = 2300.0 + float(v[5] % 800)

        # Harmonic series generated by vocal cord pulse train
        signal = np.zeros(num_samples, dtype=np.float32)
        # Sum first 12 harmonics filtered by formant resonances
        for harmonic in range(1, 13):
            harm_freq = harmonic * f0
            if harm_freq >= sample_rate / 2:
                break
            # Formant resonance filter gains (Lorentzian bandpass weighting)
            gain_f1 = 1.0 / (1.0 + ((harm_freq - f1) / 100.0) ** 2)
            gain_f2 = 0.7 / (1.0 + ((harm_freq - f2) / 140.0) ** 2)
            gain_f3 = 0.4 / (1.0 + ((harm_freq - f3) / 180.0) ** 2)
            harm_gain = gain_f1 + gain_f2 + gain_f3 + (0.2 / harmonic)

            phase = float(rng.rand() * 2 * np.pi)
            signal += (harm_gain * np.sin(2 * np.pi * harm_freq * t + phase)).astype(np.float32)

        # 3. Syllable Envelope Modulator based on words in phrase
        words = phrase.strip().split()
        num_syllables = max(2, len(words) * 2)
        syllable_freq = num_syllables / duration_sec
        # Amplitude envelope creating distinct pauses between words
        envelope = np.abs(np.sin(np.pi * syllable_freq * t)) ** 1.5
        # Smooth attack and decay at start and end
        fade_samples = int(sample_rate * 0.05)
        if fade_samples > 0 and num_samples > 2 * fade_samples:
            fade_in = np.linspace(0, 1, fade_samples, dtype=np.float32)
            fade_out = np.linspace(1, 0, fade_samples, dtype=np.float32)
            envelope[:fade_samples] *= fade_in
            envelope[-fade_samples:] *= fade_out

        modulated = signal * envelope

        # 4. Add Ambient Background Noise
        if noise_level > 0:
            noise = rng.randn(num_samples).astype(np.float32) * noise_level
            modulated += noise

        # Normalize to [-0.95, 0.95]
        max_val = float(np.max(np.abs(modulated)))
        if max_val > 1e-6:
            normalized = (modulated / max_val) * 0.95
        else:
            normalized = modulated

        return normalized.astype(np.float32)
